/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Toolkit;

/**
 *
 * @author Thili
 */
public class Calculator extends javax.swing.JFrame {
    
    String Value_1, Value_2;
    String Operator = "0";
    double Value_01, Value_02, Total;

    /**
     * Creates new form Calculator
     */
    public Calculator() {
        initComponents();
//        SetIcon();
    }
    
//    private void SetIcon() {
//        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Icon/Calculator (System Icon).png")));
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanel_Main = new javax.swing.JPanel();
        lbl_Calculator_Display = new javax.swing.JLabel();
        btn_Number_7 = new javax.swing.JButton();
        btn_Number_8 = new javax.swing.JButton();
        btn_Number_9 = new javax.swing.JButton();
        btn_Number_4 = new javax.swing.JButton();
        btn_Number_5 = new javax.swing.JButton();
        btn_Number_6 = new javax.swing.JButton();
        btn_Number_1 = new javax.swing.JButton();
        btn_Number_2 = new javax.swing.JButton();
        btn_Number_3 = new javax.swing.JButton();
        btn_Dot = new javax.swing.JButton();
        btn_Number_0 = new javax.swing.JButton();
        btn_Pluse_or_Minus = new javax.swing.JButton();
        btn_Clear = new javax.swing.JButton();
        btn_Addition = new javax.swing.JButton();
        btn_Subtraction = new javax.swing.JButton();
        btn_Division = new javax.swing.JButton();
        btn_Equal = new javax.swing.JButton();
        btn_Multiplication = new javax.swing.JButton();
        btn_Backspace = new javax.swing.JButton();
        JMenu_Bar_Main = new javax.swing.JMenuBar();
        J_File_Menu = new javax.swing.JMenu();
        J_Menu_Item_Exit = new javax.swing.JMenuItem();
        J_Help_Menu = new javax.swing.JMenu();
        J_Menu_Item_Help = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Calculator ~");

        JPanel_Main.setBackground(new java.awt.Color(102, 255, 255));
        JPanel_Main.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        lbl_Calculator_Display.setFont(new java.awt.Font("Digital-7", 1, 36)); // NOI18N
        lbl_Calculator_Display.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_Calculator_Display.setText("0");
        lbl_Calculator_Display.setToolTipText("");
        lbl_Calculator_Display.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        btn_Number_7.setFont(new java.awt.Font("Yu Gothic", 1, 16)); // NOI18N
        btn_Number_7.setText("7");
        btn_Number_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Number_7ActionPerformed(evt);
            }
        });

        btn_Number_8.setFont(new java.awt.Font("Yu Gothic", 1, 16)); // NOI18N
        btn_Number_8.setText("8");
        btn_Number_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Number_8ActionPerformed(evt);
            }
        });

        btn_Number_9.setFont(new java.awt.Font("Yu Gothic", 1, 16)); // NOI18N
        btn_Number_9.setText("9");
        btn_Number_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Number_9ActionPerformed(evt);
            }
        });

        btn_Number_4.setFont(new java.awt.Font("Yu Gothic", 1, 16)); // NOI18N
        btn_Number_4.setText("4");
        btn_Number_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Number_4ActionPerformed(evt);
            }
        });

        btn_Number_5.setFont(new java.awt.Font("Yu Gothic", 1, 16)); // NOI18N
        btn_Number_5.setText("5");
        btn_Number_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Number_5ActionPerformed(evt);
            }
        });

        btn_Number_6.setFont(new java.awt.Font("Yu Gothic", 1, 16)); // NOI18N
        btn_Number_6.setText("6");
        btn_Number_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Number_6ActionPerformed(evt);
            }
        });

        btn_Number_1.setFont(new java.awt.Font("Yu Gothic", 1, 16)); // NOI18N
        btn_Number_1.setText("1");
        btn_Number_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Number_1ActionPerformed(evt);
            }
        });

        btn_Number_2.setFont(new java.awt.Font("Yu Gothic", 1, 16)); // NOI18N
        btn_Number_2.setText("2");
        btn_Number_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Number_2ActionPerformed(evt);
            }
        });

        btn_Number_3.setFont(new java.awt.Font("Yu Gothic", 1, 16)); // NOI18N
        btn_Number_3.setText("3");
        btn_Number_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Number_3ActionPerformed(evt);
            }
        });

        btn_Dot.setFont(new java.awt.Font("Yu Gothic", 1, 16)); // NOI18N
        btn_Dot.setText(".");
        btn_Dot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DotActionPerformed(evt);
            }
        });

        btn_Number_0.setFont(new java.awt.Font("Yu Gothic", 1, 16)); // NOI18N
        btn_Number_0.setText("0");
        btn_Number_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Number_0ActionPerformed(evt);
            }
        });

        btn_Pluse_or_Minus.setFont(new java.awt.Font("Yu Gothic", 1, 16)); // NOI18N
        btn_Pluse_or_Minus.setText("+/-");
        btn_Pluse_or_Minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Pluse_or_MinusActionPerformed(evt);
            }
        });

        btn_Clear.setFont(new java.awt.Font("Yu Gothic", 1, 16)); // NOI18N
        btn_Clear.setText("C");
        btn_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ClearActionPerformed(evt);
            }
        });

        btn_Addition.setFont(new java.awt.Font("Yu Gothic", 1, 16)); // NOI18N
        btn_Addition.setText("+");
        btn_Addition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AdditionActionPerformed(evt);
            }
        });

        btn_Subtraction.setFont(new java.awt.Font("Yu Gothic", 1, 16)); // NOI18N
        btn_Subtraction.setText("-");
        btn_Subtraction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SubtractionActionPerformed(evt);
            }
        });

        btn_Division.setFont(new java.awt.Font("Yu Gothic", 1, 16)); // NOI18N
        btn_Division.setText("/");
        btn_Division.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DivisionActionPerformed(evt);
            }
        });

        btn_Equal.setFont(new java.awt.Font("Yu Gothic", 1, 16)); // NOI18N
        btn_Equal.setText("=");
        btn_Equal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EqualActionPerformed(evt);
            }
        });

        btn_Multiplication.setFont(new java.awt.Font("Yu Gothic", 1, 16)); // NOI18N
        btn_Multiplication.setText("*");
        btn_Multiplication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MultiplicationActionPerformed(evt);
            }
        });

        btn_Backspace.setFont(new java.awt.Font("Yu Gothic", 1, 16)); // NOI18N
        btn_Backspace.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Backspace_Icon.png"))); // NOI18N
        btn_Backspace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BackspaceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPanel_MainLayout = new javax.swing.GroupLayout(JPanel_Main);
        JPanel_Main.setLayout(JPanel_MainLayout);
        JPanel_MainLayout.setHorizontalGroup(
            JPanel_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanel_MainLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(JPanel_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_Calculator_Display, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(JPanel_MainLayout.createSequentialGroup()
                        .addGroup(JPanel_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(JPanel_MainLayout.createSequentialGroup()
                                .addGroup(JPanel_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btn_Dot, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                                    .addComponent(btn_Number_1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                                    .addComponent(btn_Number_4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                                    .addComponent(btn_Number_7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(JPanel_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btn_Number_8, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                                    .addComponent(btn_Number_5, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                                    .addComponent(btn_Number_2, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                                    .addComponent(btn_Number_0, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)))
                            .addComponent(btn_Equal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(JPanel_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JPanel_MainLayout.createSequentialGroup()
                                .addGroup(JPanel_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btn_Number_9, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                                    .addComponent(btn_Number_6, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                                    .addComponent(btn_Number_3, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                                    .addComponent(btn_Pluse_or_Minus, javax.swing.GroupLayout.PREFERRED_SIZE, 60, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(JPanel_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btn_Addition, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                                    .addComponent(btn_Subtraction, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                                    .addComponent(btn_Clear, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                                    .addComponent(btn_Backspace, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)))
                            .addGroup(JPanel_MainLayout.createSequentialGroup()
                                .addComponent(btn_Multiplication, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_Division, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JPanel_MainLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btn_Addition, btn_Backspace, btn_Clear, btn_Division, btn_Dot, btn_Multiplication, btn_Number_0, btn_Number_1, btn_Number_2, btn_Number_3, btn_Number_4, btn_Number_5, btn_Number_6, btn_Number_7, btn_Number_8, btn_Number_9, btn_Pluse_or_Minus, btn_Subtraction});

        JPanel_MainLayout.setVerticalGroup(
            JPanel_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanel_MainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_Calculator_Display, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JPanel_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_Number_7, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addGroup(JPanel_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_Number_8, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                        .addComponent(btn_Number_9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_Backspace, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JPanel_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_Number_4, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(btn_Number_5, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addGroup(JPanel_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_Number_6, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                        .addComponent(btn_Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(JPanel_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Number_2, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addGroup(JPanel_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_Number_3, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                        .addComponent(btn_Addition, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                    .addComponent(btn_Number_1, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(JPanel_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Dot, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(btn_Number_0, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(btn_Pluse_or_Minus, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(btn_Subtraction, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JPanel_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Equal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Multiplication, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(btn_Division, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                .addContainerGap())
        );

        JPanel_MainLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btn_Addition, btn_Backspace, btn_Clear, btn_Division, btn_Dot, btn_Equal, btn_Multiplication, btn_Number_0, btn_Number_1, btn_Number_2, btn_Number_3, btn_Number_4, btn_Number_5, btn_Number_6, btn_Number_7, btn_Number_8, btn_Number_9, btn_Pluse_or_Minus, btn_Subtraction});

        JMenu_Bar_Main.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        J_File_Menu.setText("File");

        J_Menu_Item_Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Close.png"))); // NOI18N
        J_Menu_Item_Exit.setText("Exit");
        J_Menu_Item_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                J_Menu_Item_ExitActionPerformed(evt);
            }
        });
        J_File_Menu.add(J_Menu_Item_Exit);

        JMenu_Bar_Main.add(J_File_Menu);

        J_Help_Menu.setText("Help");

        J_Menu_Item_Help.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Hep.png"))); // NOI18N
        J_Menu_Item_Help.setText("Help");
        J_Help_Menu.add(J_Menu_Item_Help);

        JMenu_Bar_Main.add(J_Help_Menu);

        setJMenuBar(JMenu_Bar_Main);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanel_Main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanel_Main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_Number_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Number_7ActionPerformed
        if (lbl_Calculator_Display.getText().equals("0")) {
            lbl_Calculator_Display.setText("");
            lbl_Calculator_Display.setText(lbl_Calculator_Display.getText() + btn_Number_7.getText());
        } else {
            lbl_Calculator_Display.setText(lbl_Calculator_Display.getText() + btn_Number_7.getText());
        }
    }//GEN-LAST:event_btn_Number_7ActionPerformed

    private void btn_Number_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Number_8ActionPerformed
        if (lbl_Calculator_Display.getText().equals("0")) {
            lbl_Calculator_Display.setText("");
            lbl_Calculator_Display.setText(lbl_Calculator_Display.getText() + btn_Number_8.getText());
        } else {
            lbl_Calculator_Display.setText(lbl_Calculator_Display.getText() + btn_Number_8.getText());
        }
    }//GEN-LAST:event_btn_Number_8ActionPerformed

    private void btn_Number_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Number_9ActionPerformed
        if (lbl_Calculator_Display.getText().equals("0")) {
            lbl_Calculator_Display.setText("");
            lbl_Calculator_Display.setText(lbl_Calculator_Display.getText() + btn_Number_9.getText());
        } else {
            lbl_Calculator_Display.setText(lbl_Calculator_Display.getText() + btn_Number_9.getText());
        }
    }//GEN-LAST:event_btn_Number_9ActionPerformed

    private void btn_Number_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Number_4ActionPerformed
        if (lbl_Calculator_Display.getText().equals("0")) {
            lbl_Calculator_Display.setText("");
            lbl_Calculator_Display.setText(lbl_Calculator_Display.getText() + btn_Number_4.getText());
        } else {
            lbl_Calculator_Display.setText(lbl_Calculator_Display.getText() + btn_Number_4.getText());
        }
    }//GEN-LAST:event_btn_Number_4ActionPerformed

    private void btn_Number_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Number_5ActionPerformed
        if (lbl_Calculator_Display.getText().equals("0")) {
            lbl_Calculator_Display.setText("");
            lbl_Calculator_Display.setText(lbl_Calculator_Display.getText() + btn_Number_5.getText());
        } else {
            lbl_Calculator_Display.setText(lbl_Calculator_Display.getText() + btn_Number_5.getText());
        }
    }//GEN-LAST:event_btn_Number_5ActionPerformed

    private void btn_Number_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Number_6ActionPerformed
        if (lbl_Calculator_Display.getText().equals("0")) {
            lbl_Calculator_Display.setText("");
            lbl_Calculator_Display.setText(lbl_Calculator_Display.getText() + btn_Number_6.getText());
        } else {
            lbl_Calculator_Display.setText(lbl_Calculator_Display.getText() + btn_Number_6.getText());
        }
    }//GEN-LAST:event_btn_Number_6ActionPerformed

    private void btn_Number_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Number_1ActionPerformed
        if (lbl_Calculator_Display.getText().equals("0")) {
            lbl_Calculator_Display.setText("");
            lbl_Calculator_Display.setText(lbl_Calculator_Display.getText() + btn_Number_1.getText());
        } else {
            lbl_Calculator_Display.setText(lbl_Calculator_Display.getText() + btn_Number_1.getText());
        }
    }//GEN-LAST:event_btn_Number_1ActionPerformed

    private void btn_Number_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Number_2ActionPerformed
        if (lbl_Calculator_Display.getText().equals("0")) {
            lbl_Calculator_Display.setText("");
            lbl_Calculator_Display.setText(lbl_Calculator_Display.getText() + btn_Number_2.getText());
        } else {
            lbl_Calculator_Display.setText(lbl_Calculator_Display.getText() + btn_Number_2.getText());
        }
    }//GEN-LAST:event_btn_Number_2ActionPerformed

    private void btn_Number_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Number_3ActionPerformed
        if (lbl_Calculator_Display.getText().equals("0")) {
            lbl_Calculator_Display.setText("");
            lbl_Calculator_Display.setText(lbl_Calculator_Display.getText() + btn_Number_3.getText());
        } else {
            lbl_Calculator_Display.setText(lbl_Calculator_Display.getText() + btn_Number_3.getText());
        }
    }//GEN-LAST:event_btn_Number_3ActionPerformed

    private void btn_DotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DotActionPerformed
        lbl_Calculator_Display.setText(lbl_Calculator_Display.getText() + btn_Dot.getText());
    }//GEN-LAST:event_btn_DotActionPerformed

    private void btn_Number_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Number_0ActionPerformed
        if (lbl_Calculator_Display.getText().equals("0")) {
            lbl_Calculator_Display.setText("");
            lbl_Calculator_Display.setText(lbl_Calculator_Display.getText() + btn_Number_0.getText());
        } else {
            lbl_Calculator_Display.setText(lbl_Calculator_Display.getText() + btn_Number_0.getText());
        }
    }//GEN-LAST:event_btn_Number_0ActionPerformed

    private void btn_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ClearActionPerformed
        lbl_Calculator_Display.setText("0");
        Operator = "0";
        Value_01 = 0;
        Value_02 = 0;
        Value_1 = "";
        Value_2 = "";
        Total = 0;
    }//GEN-LAST:event_btn_ClearActionPerformed

    private void btn_Pluse_or_MinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Pluse_or_MinusActionPerformed
        char sign = lbl_Calculator_Display.getText().charAt(0);
        if (sign == '-') {
            lbl_Calculator_Display.setText(lbl_Calculator_Display.getText().substring(1, lbl_Calculator_Display.getText().length()));
        } else {
            lbl_Calculator_Display.setText("-" + lbl_Calculator_Display.getText());
        }
    }//GEN-LAST:event_btn_Pluse_or_MinusActionPerformed

    private void btn_SubtractionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SubtractionActionPerformed
        Value_1 = lbl_Calculator_Display.getText();
        Operator = "-";
        lbl_Calculator_Display.setText("0");
    }//GEN-LAST:event_btn_SubtractionActionPerformed

    private void btn_EqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EqualActionPerformed
        if (Operator.equals("0")) {
            System.out.println("OK");
            lbl_Calculator_Display.setText("Not Operator Select");
        } else {
            if (Operator.equals("+")) {
                Value_2 = lbl_Calculator_Display.getText();
                lbl_Calculator_Display.setText("0");
                Value_01 = Double.parseDouble(Value_1);
                Value_02 = Double.parseDouble(Value_2);
                Total = Value_01 + Value_02;
                lbl_Calculator_Display.setText(Total + "");
                char Last_Char = lbl_Calculator_Display.getText().charAt(lbl_Calculator_Display.getText().length() - 1);
                if (Last_Char == '0') {
                    lbl_Calculator_Display.setText(lbl_Calculator_Display.getText().substring(0, lbl_Calculator_Display.getText().length() - 2));
                }
                Value_01 = 0;
                Value_02 = 0;
                Value_1 = "";
                Value_2 = "";
            } else if (Operator.equals("-")) {
                Value_2 = lbl_Calculator_Display.getText();
                lbl_Calculator_Display.setText("0");
                Value_01 = Double.parseDouble(Value_1);
                Value_02 = Double.parseDouble(Value_2);
                Total = Value_01 - Value_02;
                lbl_Calculator_Display.setText(Total + "");
                char Last_Char = lbl_Calculator_Display.getText().charAt(lbl_Calculator_Display.getText().length() - 1);
                if (Last_Char == '0') {
                    lbl_Calculator_Display.setText(lbl_Calculator_Display.getText().substring(0, lbl_Calculator_Display.getText().length() - 2));
                }
                Value_01 = 0.0;
                Value_02 = 0.0;
                Value_1 = "";
                Value_2 = "";
            } else if (Operator.equals("/")) {
                Value_2 = lbl_Calculator_Display.getText();
                lbl_Calculator_Display.setText("0");
                Value_01 = Double.parseDouble(Value_1);
                Value_02 = Double.parseDouble(Value_2);
                Total = Value_01 / Value_02;
                lbl_Calculator_Display.setText(Total + "");
                char Last_Char = lbl_Calculator_Display.getText().charAt(lbl_Calculator_Display.getText().length() - 1);
                if (Last_Char == '0') {
                    lbl_Calculator_Display.setText(lbl_Calculator_Display.getText().substring(0, lbl_Calculator_Display.getText().length() - 2));
                }
                Value_01 = 0.0;
                Value_02 = 0.0;
                Value_1 = "";
                Value_2 = "";
            } else if (Operator.equals("*")) {
                Value_2 = lbl_Calculator_Display.getText();
                lbl_Calculator_Display.setText("0");
                Value_01 = Double.parseDouble(Value_1);
                Value_02 = Double.parseDouble(Value_2);
                Total = Value_01 * Value_02;
                lbl_Calculator_Display.setText(Total + "");
                char Last_Char = lbl_Calculator_Display.getText().charAt(lbl_Calculator_Display.getText().length() - 1);
                if (Last_Char == '0') {
                    lbl_Calculator_Display.setText(lbl_Calculator_Display.getText().substring(0, lbl_Calculator_Display.getText().length() - 2));
                }
                Value_01 = 0.0;
                Value_02 = 0.0;
                Value_1 = "";
                Value_2 = "";
            } else {
                System.out.println("Operator Not Match");
            }
        }
    }//GEN-LAST:event_btn_EqualActionPerformed

    private void btn_AdditionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AdditionActionPerformed
        Value_1 = lbl_Calculator_Display.getText();
        Operator = "+";
        lbl_Calculator_Display.setText("0");
    }//GEN-LAST:event_btn_AdditionActionPerformed

    private void btn_DivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DivisionActionPerformed
        Value_1 = lbl_Calculator_Display.getText();
        Operator = "/";
        lbl_Calculator_Display.setText("0");
    }//GEN-LAST:event_btn_DivisionActionPerformed

    private void btn_MultiplicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MultiplicationActionPerformed
        Value_1 = lbl_Calculator_Display.getText();
        Operator = "*";
        lbl_Calculator_Display.setText("0");
    }//GEN-LAST:event_btn_MultiplicationActionPerformed

    private void btn_BackspaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BackspaceActionPerformed
        if (lbl_Calculator_Display.getText().equals("")) {
            lbl_Calculator_Display.setText("0");
            System.out.println("Display Empty");
        } else {
            lbl_Calculator_Display.setText(lbl_Calculator_Display.getText().substring(0, lbl_Calculator_Display.getText().length() - 1));
        }
    }//GEN-LAST:event_btn_BackspaceActionPerformed

    private void J_Menu_Item_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_J_Menu_Item_ExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_J_Menu_Item_ExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar JMenu_Bar_Main;
    private javax.swing.JPanel JPanel_Main;
    private javax.swing.JMenu J_File_Menu;
    private javax.swing.JMenu J_Help_Menu;
    private javax.swing.JMenuItem J_Menu_Item_Exit;
    private javax.swing.JMenuItem J_Menu_Item_Help;
    private javax.swing.JButton btn_Addition;
    private javax.swing.JButton btn_Backspace;
    private javax.swing.JButton btn_Clear;
    private javax.swing.JButton btn_Division;
    private javax.swing.JButton btn_Dot;
    private javax.swing.JButton btn_Equal;
    private javax.swing.JButton btn_Multiplication;
    private javax.swing.JButton btn_Number_0;
    private javax.swing.JButton btn_Number_1;
    private javax.swing.JButton btn_Number_2;
    private javax.swing.JButton btn_Number_3;
    private javax.swing.JButton btn_Number_4;
    private javax.swing.JButton btn_Number_5;
    private javax.swing.JButton btn_Number_6;
    private javax.swing.JButton btn_Number_7;
    private javax.swing.JButton btn_Number_8;
    private javax.swing.JButton btn_Number_9;
    private javax.swing.JButton btn_Pluse_or_Minus;
    private javax.swing.JButton btn_Subtraction;
    private javax.swing.JLabel lbl_Calculator_Display;
    // End of variables declaration//GEN-END:variables
}
